# Generated by Django 4.2.27 on 2026-01-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_noteanalysis_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteanalysis',
            name='raw_text',
            field=models.TextField(blank=True, help_text='Original notes submitted by the user'),
        ),
    ]
