# Generated by Django 4.2.27 on 2026-01-13 17:01

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_noteanalysis_raw_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteanalysis',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=core.models.upload_to),
        ),
    ]
